const fs = require('fs');
const path = require('path');
const dir = process.env.OUTPUT_DIR || path.join(__dirname, 'all-platform-files');

const platforms = [
  // === EU MARKETPLACES (20) ===
  {id:'ebay',name:'eBay',color:'#E53238',steps:62,sections:10,users:'135M+ Buyers',desc:'Global Marketplace อันดับ 2 โลก',phases:['สมัครบัญชี (6)','เปิดร้าน eBay Store (7)','ยืนยันตัวตน (5)','เพิ่มสินค้า Listing [AI] (9)','ตั้งค่าจัดส่ง International (5)','โปรโมชั่น Promoted Listings (4)','รับออร์เดอร์ (5)','ชำระเงิน PayPal/Payoneer (5)','จัดส่ง Global Shipping (5)','หลังการขาย Feedback (5)']},
  {id:'etsy',name:'Etsy',color:'#F1641E',steps:58,sections:9,users:'90M+ Buyers',desc:'Handmade + Vintage Marketplace โลก',phases:['สมัครบัญชี (6)','เปิดร้าน Etsy Shop (7)','เพิ่มสินค้า [AI] (9)','Etsy SEO + Tags [AI] (6)','โปรโมชั่น Etsy Ads (4)','รับออร์เดอร์ (5)','ชำระเงิน Etsy Payments (5)','จัดส่ง (5)','หลังการขาย Reviews (5)']},
  {id:'cdiscount',name:'Cdiscount',color:'#00539F',steps:55,sections:9,users:'23M+ Buyers',desc:'Marketplace อันดับ 2 ฝรั่งเศส',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า [AI] (8)','ตั้งค่าจัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','จัดส่ง (5)','หลังการขาย (4)']},
  {id:'fnac',name:'FnacDarty',color:'#E4A800',steps:52,sections:8,users:'20M+ Buyers',desc:'Electronics + Culture Marketplace ฝรั่งเศส',phases:['สมัคร Seller (7)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า [AI] (8)','ตั้งค่าจัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'laredoute',name:'LaRedoute',color:'#D4002A',steps:48,sections:8,users:'10M+ Buyers',desc:'Fashion + Home Marketplace ฝรั่งเศส',phases:['สมัคร Seller (6)','ยืนยันแบรนด์ (5)','เพิ่มสินค้า [AI] (7)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (4)','หลังการขาย (4)']},
  {id:'veepee',name:'Veepee',color:'#FF007C',steps:45,sections:7,users:'70M+ Members',desc:'Flash Sale Marketplace ยุโรป (Vente-Privée)',phases:['สมัคร Brand Partner (7)','ยืนยันแบรนด์ (5)','เตรียมสินค้า Flash Sale (6)','ตั้งค่าจัดส่ง (5)','จัด Flash Sale Event (5)','ชำระเงิน (4)','หลังการขาย (4)']},
  {id:'elcorteingles',name:'ElCorteIngles',color:'#006633',steps:50,sections:8,users:'15M+ Buyers',desc:'Department Store Marketplace สเปน',phases:['สมัคร Seller (7)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า [AI] (7)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'allegro',name:'Allegro',color:'#FF5A00',steps:58,sections:9,users:'22M+ Buyers',desc:'Marketplace อันดับ 1 โปแลนด์',phases:['สมัคร Seller (6)','ยืนยันตัวตน (5)','เพิ่มสินค้า [AI] (8)','ตั้งค่าจัดส่ง (5)','Allegro Ads (4)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (5)']},
  {id:'zalando',name:'Zalando',color:'#FF6900',steps:55,sections:9,users:'50M+ Customers',desc:'Fashion Marketplace อันดับ 1 ยุโรป',phases:['สมัคร Partner Program (7)','ยืนยันแบรนด์ (5)','เพิ่มสินค้า [AI] (8)','Zalando Fulfillment (5)','โปรโมชั่น (4)','Marketing ZMS (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'bol',name:'Bol',color:'#0000A4',steps:55,sections:9,users:'13M+ Buyers',desc:'Marketplace อันดับ 1 เนเธอร์แลนด์/เบลเยียม',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ EU (5)','เพิ่มสินค้า [AI] (8)','Logistics via Bol (5)','โปรโมชั่น (4)','Bol Ads (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (5)']},
  {id:'asos',name:'ASOS',color:'#2D2D2D',steps:48,sections:8,users:'26M+ Customers',desc:'Fashion Marketplace UK/Global',phases:['สมัคร ASOS Marketplace (6)','ยืนยันแบรนด์ (5)','เพิ่มสินค้า [AI] (7)','ตั้งค่าจัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (4)','หลังการขาย (4)']},
  {id:'otto',name:'OTTO',color:'#E60000',steps:52,sections:8,users:'12M+ Buyers',desc:'Marketplace อันดับ 2 เยอรมนี',phases:['สมัคร Partner (7)','ยืนยันธุรกิจ EU (5)','เพิ่มสินค้า [AI] (8)','Logistics OTTO Fulfillment (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'manomano',name:'ManoMano',color:'#00B2A9',steps:50,sections:8,users:'7M+ Buyers',desc:'DIY + Garden Marketplace ยุโรป',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า DIY [AI] (8)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'emag',name:'Emag',color:'#2196F3',steps:52,sections:8,users:'15M+ Buyers',desc:'Marketplace อันดับ 1 โรมาเนีย/ยุโรปตะวันออก',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า [AI] (8)','จัดส่ง Emag Fulfillment (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (5)']},
  {id:'leroymerlin',name:'LeroyMerlin',color:'#78BE20',steps:48,sections:7,users:'10M+ Buyers',desc:'Home + DIY Marketplace ยุโรป',phases:['สมัคร Seller (7)','ยืนยันสินค้า (5)','เพิ่มสินค้า [AI] (8)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์+ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'kaufland',name:'Kaufland',color:'#E10019',steps:52,sections:8,users:'32M+ Visitors/mo',desc:'Marketplace เยอรมนี (Real.de เดิม)',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ EU (5)','เพิ่มสินค้า [AI] (8)','จัดส่ง (5)','Kaufland Ads (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (5)']},
  {id:'digitec',name:'DigitecGalaxus',color:'#2D9CDB',steps:48,sections:8,users:'6M+ Buyers',desc:'Marketplace อันดับ 1 สวิตเซอร์แลนด์',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า [AI] (7)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน CHF (4)','หลังการขาย (4)']},
  {id:'argos',name:'Argos',color:'#D42F2F',steps:48,sections:7,users:'30M+ Visitors/mo',desc:'Retail Marketplace UK (Sainsbury)',phases:['สมัคร Partner (7)','ยืนยันธุรกิจ UK (5)','เพิ่มสินค้า [AI] (8)','จัดส่ง UK (5)','โปรโมชั่น (4)','รับออร์เดอร์+ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'alza',name:'Alza',color:'#84C225',steps:48,sections:8,users:'11M+ Visitors/mo',desc:'Electronics Marketplace เช็ก/สโลวัก',phases:['สมัคร Seller (6)','ยืนยันธุรกิจ (5)','เพิ่มสินค้า (7)','จัดส่ง (5)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน CZK (4)','หลังการขาย (4)']},
  {id:'heureka',name:'Heureka',color:'#63A615',steps:42,sections:7,users:'10M+ Visitors/mo',desc:'Price Comparison + Marketplace เช็ก/สโลวัก',phases:['สมัครบัญชี (5)','เชื่อม Product Feed (6)','Heureka SEO [AI] (6)','Heureka Ads (4)','รับ Traffic+ออร์เดอร์ (5)','ชำระเงิน (4)','หลังการขาย (4)']},

  // === E-COMMERCE PLATFORMS (11) ===
  {id:'shopify',name:'Shopify',color:'#7AB55C',steps:65,sections:10,users:'4.4M+ Stores',desc:'E-commerce Platform อันดับ 1 โลก',phases:['สมัครบัญชี (5)','เลือก Plan + ตั้งค่าร้าน (7)','เพิ่มสินค้า [AI] (8)','ตั้งค่า Theme/Design (6)','Payment Gateway (5)','จัดส่ง (5)','Marketing+SEO [AI] (7)','เชื่อม Marketplace (5)','รับออร์เดอร์+ชำระเงิน (5)','Analytics (5)']},
  {id:'woocommerce',name:'WooCommerce',color:'#96588A',steps:62,sections:10,users:'5M+ Stores',desc:'WordPress E-commerce Plugin อันดับ 1',phases:['ติดตั้ง WordPress+WooCommerce (7)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (8)','Theme/Design (5)','Payment Gateway (5)','จัดส่ง (5)','SEO+Marketing [AI] (7)','เชื่อม Marketplace (4)','รับออร์เดอร์ (5)','Analytics (5)']},
  {id:'prestashop',name:'PrestaShop',color:'#DF0067',steps:58,sections:9,users:'300K+ Stores',desc:'Open Source E-commerce ยุโรป',phases:['ติดตั้ง PrestaShop (6)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (8)','Theme/Module (5)','Payment (5)','จัดส่ง (5)','SEO [AI] (6)','รับออร์เดอร์ (5)','Analytics (5)']},
  {id:'magento',name:'Magento',color:'#F46F25',steps:65,sections:10,users:'250K+ Stores',desc:'Adobe Commerce Enterprise E-commerce',phases:['ติดตั้ง Magento/Adobe Commerce (7)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (8)','Theme/Extension (6)','Payment (5)','จัดส่ง (5)','SEO+Marketing [AI] (7)','เชื่อม Marketplace (5)','รับออร์เดอร์ (5)','Analytics (5)']},
  {id:'opencart',name:'OpenCart',color:'#35AADB',steps:55,sections:9,users:'400K+ Stores',desc:'Open Source E-commerce ง่าย+ฟรี',phases:['ติดตั้ง OpenCart (6)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (8)','Theme/Extension (5)','Payment (5)','จัดส่ง (5)','SEO [AI] (6)','รับออร์เดอร์ (5)','Analytics (4)']},
  {id:'shopware',name:'Shopware',color:'#189EFF',steps:58,sections:9,users:'100K+ Stores',desc:'E-commerce Platform เยอรมนี Enterprise',phases:['ติดตั้ง Shopware (6)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (8)','Theme/Plugin (5)','Payment (5)','จัดส่ง (5)','SEO+Marketing [AI] (7)','รับออร์เดอร์ (5)','Analytics (5)']},
  {id:'lightspeed',name:'Lightspeed',color:'#DB2828',steps:55,sections:9,users:'200K+ Stores',desc:'POS + E-commerce Omnichannel',phases:['สมัครบัญชี (5)','ตั้งค่าร้าน+POS (6)','เพิ่มสินค้า [AI] (8)','Theme (5)','Payment+POS (5)','จัดส่ง (5)','Marketing [AI] (6)','รับออร์เดอร์ (5)','Analytics (4)']},
  {id:'ecwid',name:'Ecwid',color:'#2D71CF',steps:50,sections:8,users:'200K+ Stores',desc:'E-commerce ฝังในเว็บ/Social ง่ายที่สุด',phases:['สมัครบัญชี (5)','ฝัง Store ในเว็บ/FB/IG (6)','เพิ่มสินค้า [AI] (7)','Design (4)','Payment (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์+Analytics (5)']},
  {id:'squarespace',name:'Squarespace',color:'#000000',steps:52,sections:8,users:'4M+ Websites',desc:'Website Builder + E-commerce สวยที่สุด',phases:['สมัครบัญชี (5)','เลือก Template+Design (6)','เพิ่มสินค้า [AI] (7)','ตั้งค่า Commerce (5)','Payment Stripe/PayPal (5)','จัดส่ง (5)','SEO+Marketing [AI] (6)','รับออร์เดอร์+Analytics (5)']},
  {id:'wix',name:'Wix',color:'#0C6EFC',steps:52,sections:8,users:'200M+ Users',desc:'Website Builder + E-commerce ง่ายที่สุด',phases:['สมัครบัญชี (5)','เลือก Template+Design (6)','เพิ่มสินค้า [AI] (7)','Wix Stores ตั้งค่า (5)','Payment (5)','จัดส่ง (5)','SEO+Marketing [AI] (6)','รับออร์เดอร์+Analytics (5)']},
  {id:'wordpress',name:'WordPress',color:'#21759B',steps:55,sections:8,users:'800M+ Websites',desc:'CMS อันดับ 1 โลก + E-commerce via Plugin',phases:['ติดตั้ง WordPress (6)','เลือก Theme+Plugin (6)','เพิ่มสินค้า WooCommerce [AI] (8)','SEO Yoast/RankMath [AI] (6)','Payment (5)','จัดส่ง (5)','Marketing+Content [AI] (7)','รับออร์เดอร์+Analytics (5)']},

  // === EU LOCAL E-COM PLATFORMS (23) ===
  {id:'dandomain',name:'Dandomain',color:'#E74C3C',steps:45,sections:7,users:'DK E-com',desc:'E-commerce Platform อันดับ 1 เดนมาร์ก',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment DK (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'voog',name:'Voog',color:'#4A90D9',steps:42,sections:7,users:'EE E-com',desc:'Website+E-commerce Platform เอสโตเนีย',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'cloudcart',name:'CloudCart',color:'#FF6B00',steps:45,sections:7,users:'BG E-com',desc:'E-commerce Platform บัลแกเรีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'peppershop',name:'PepperShop',color:'#E53935',steps:45,sections:7,users:'CH E-com',desc:'E-commerce Platform สวิตเซอร์แลนด์',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment CHF (5)','จัดส่ง Swiss Post (5)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'jtlshop',name:'JTLShop',color:'#1565C0',steps:52,sections:8,users:'DE E-com',desc:'E-commerce + ERP Platform เยอรมนี',phases:['ติดตั้ง JTL-Shop (6)','ตั้งค่าร้าน+ERP (6)','เพิ่มสินค้า [AI] (7)','เชื่อม Marketplace DE (5)','Payment (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์ (5)']},
  {id:'epages',name:'ePages',color:'#00BCD4',steps:45,sections:7,users:'DE E-com',desc:'SaaS E-commerce Platform เยอรมนี',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'optimizely',name:'Optimizely',color:'#0037FF',steps:48,sections:7,users:'SE/EU E-com',desc:'DXP + Commerce Platform สวีเดน (Episerver)',phases:['ติดตั้ง (6)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','A/B Test+Marketing [AI] (6)','รับออร์เดอร์ (5)']},
  {id:'mycashflow',name:'MyCashFlow',color:'#F57C00',steps:42,sections:7,users:'FI E-com',desc:'E-commerce Platform ฟินแลนด์',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment FI (5)','จัดส่ง (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'vilkas',name:'Vilkas',color:'#7B1FA2',steps:42,sections:7,users:'FI E-com',desc:'E-commerce Platform ฟินแลนด์',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment FI (5)','จัดส่ง Posti (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'shoprenter',name:'Shoprenter',color:'#FF5722',steps:45,sections:7,users:'HU E-com',desc:'E-commerce Platform ฮังการี',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment HUF (5)','จัดส่ง (5)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'shoptet',name:'Shoptet',color:'#00C853',steps:48,sections:8,users:'CZ E-com 35K+',desc:'E-commerce Platform อันดับ 1 เช็ก',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment CZK (5)','จัดส่ง (5)','เชื่อม Heureka/Alza (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'shopiteka',name:'Shopiteka',color:'#3F51B5',steps:40,sections:6,users:'LT E-com',desc:'E-commerce Platform ลิทัวเนีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','รับออร์เดอร์ (4)']},
  {id:'verskis',name:'Verskis',color:'#009688',steps:40,sections:6,users:'LT E-com',desc:'E-commerce Platform ลิทัวเนีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','รับออร์เดอร์ (4)']},
  {id:'mozello',name:'Mozello',color:'#FF9800',steps:40,sections:6,users:'LV E-com',desc:'Website+E-commerce Platform ลัตเวีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','รับออร์เดอร์ (4)']},
  {id:'myonlinestore',name:'MyOnlineStore',color:'#2196F3',steps:42,sections:7,users:'NL E-com',desc:'E-commerce Platform เนเธอร์แลนด์',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment iDEAL (5)','จัดส่ง PostNL (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'nettbutikk24',name:'24Nettbutikk',color:'#E91E63',steps:42,sections:7,users:'NO E-com',desc:'E-commerce Platform นอร์เวย์',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment NOK (5)','จัดส่ง Posten (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'merchantpro',name:'MerchantPro',color:'#673AB7',steps:45,sections:7,users:'RO E-com',desc:'E-commerce Platform โรมาเนีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment RON (5)','จัดส่ง (5)','Marketing+Emag [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'gomag',name:'Gomag',color:'#4CAF50',steps:45,sections:7,users:'RO E-com',desc:'E-commerce Platform โรมาเนีย',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment RON (5)','จัดส่ง (5)','Marketing+Emag [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'oscommerce',name:'osCommerce',color:'#003D6A',steps:50,sections:8,users:'Open Source',desc:'Open Source E-commerce เก่าแก่ที่สุด',phases:['ติดตั้ง osCommerce (6)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Theme/Module (5)','Payment (5)','จัดส่ง (5)','SEO [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'quickbutik',name:'Quickbutik',color:'#2196F3',steps:42,sections:7,users:'SE E-com',desc:'E-commerce Platform สวีเดน',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment SEK (5)','จัดส่ง (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'wikinggruppen',name:'Wikinggruppen',color:'#FF5722',steps:40,sections:6,users:'SE E-com',desc:'E-commerce Agency สวีเดน',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','รับออร์เดอร์ (4)']},
  {id:'eshoprychle',name:'eShopRychle',color:'#8BC34A',steps:42,sections:7,users:'SK/CZ E-com',desc:'E-commerce Platform สโลวัก/เช็ก',phases:['สมัคร (5)','ตั้งค่าร้าน (5)','เพิ่มสินค้า [AI] (7)','Payment CZK/EUR (5)','จัดส่ง (4)','Marketing [AI] (5)','รับออร์เดอร์ (4)']},
  {id:'webarial',name:'Webarial',color:'#607D8B',steps:40,sections:6,users:'SK E-com',desc:'E-commerce Platform สโลวัก',phases:['สมัคร (5)','ตั้งค่าร้าน (6)','เพิ่มสินค้า [AI] (7)','Payment (5)','จัดส่ง (5)','รับออร์เดอร์ (4)']},

  // === SOCIAL / NEW (4) ===
  {id:'linkedin',name:'LinkedIn',color:'#0077B5',steps:55,sections:9,users:'1,000M+ Users',desc:'Professional Network อันดับ 1 โลก B2B',phases:['สมัครบัญชี (5)','ตั้งค่า Company Page (6)','สร้าง Content B2B [AI] (7)','LinkedIn Ads (5)','LinkedIn Sales Navigator (5)','Networking+Outreach [AI] (5)','ดึง Traffic B2B (5)','รับออร์เดอร์ B2B (5)','หลังการขาย (4)']},
  {id:'mastodon',name:'Mastodon',color:'#6364FF',steps:38,sections:6,users:'12M+ Users',desc:'Decentralized Social Network (Fediverse)',phases:['สมัครบัญชี Instance (6)','ตั้งค่าโปรไฟล์ (5)','สร้าง Content [AI] (7)','Community Engagement (5)','ดึง Traffic ไปร้านค้า (5)','รับออร์เดอร์ (4)']},
  {id:'bluesky',name:'Bluesky',color:'#0085FF',steps:40,sections:7,users:'25M+ Users',desc:'Decentralized Social (AT Protocol)',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (5)','สร้าง Content [AI] (7)','Engagement (5)','ดึง Traffic (5)','รับออร์เดอร์ (4)','หลังการขาย (3)']},
  {id:'eurosky',name:'Eurosky',color:'#003399',steps:35,sections:6,users:'EU Social',desc:'European Social Platform',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (4)','สร้าง Content [AI] (7)','Engagement (5)','ดึง Traffic (5)','รับออร์เดอร์ (3)']}
];

let created = 0;
platforms.forEach(p => {
  // HTML Section
  const html = `<!-- Openthai.ai - ${p.name} Roadmap -->\n<section id="${p.id}-roadmap" style="max-width:900px;margin:2rem auto;padding:2rem;font-family:'Sarabun',sans-serif;background:#f8f9fa;border-radius:16px;">\n<h2 style="text-align:center;color:${p.color};font-size:2rem;">${p.name} — ${p.steps} ขั้นตอน</h2>\n<p style="text-align:center;color:#666;">${p.desc} | ${p.users}</p>\n<div style="background:#fff;padding:1.5rem;border-radius:12px;border-left:4px solid ${p.color};margin-top:1rem;">\n<ol>${p.phases.map((ph,i) => `<li style="padding:4px 0;"><strong>ส่วนที่ ${i+1}</strong> — ${ph}</li>`).join('\n')}</ol>\n</div>\n<div style="text-align:center;margin-top:1.5rem;padding:1rem;background:${p.color};border-radius:12px;">\n<p style="color:#fff;margin:0;">🤖 Openthai.ai ช่วยสร้าง Content ได้ทุกภาษา</p>\n<a href="/generate" style="display:inline-block;margin-top:8px;padding:10px 24px;background:#fff;color:${p.color};border-radius:20px;text-decoration:none;font-weight:bold;">สร้าง Content ${p.name} →</a>\n</div>\n</section>`;
  fs.writeFileSync(dir + '/' + p.id + '-roadmap-section.html', html);

  // HTML Guide
  const guide = `<html><head><meta charset="utf-8"><style>body{font-family:Sarabun,sans-serif;max-width:700px;margin:0 auto;padding:20px;line-height:1.6}h1{color:${p.color};border-bottom:3px solid ${p.color}}h3{margin-top:16px}</style></head><body><h1>${p.name} Roadmap</h1><p>${p.desc} | ${p.users}</p><p><strong>${p.steps} ขั้นตอน | ${p.sections} ส่วน</strong></p>${p.phases.map((ph,i) => `<h3>ส่วนที่ ${i+1} — ${ph}</h3>`).join('')}<hr><p><em>สร้างโดย Openthai.ai — www.Openthai.ai.com</em></p></body></html>`;
  fs.writeFileSync(dir + '/Openthai.ai_' + p.name + '_Roadmap.html', guide);

  created++;
  console.log(created + '. ' + p.name + ' ✓');
});

console.log('\n=== DONE: ' + created + ' platforms ===');
console.log('Total steps: ' + platforms.reduce((s,p) => s + p.steps, 0));
