const fs = require('fs');
const dir = 'C:/Openthai.ai/all-platform-files';

const platforms = [
  {id:'carousell',name:'Carousell',color:'#FF4747',icon:'SG',steps:45,sections:8,users:'30M+',desc:'C2C Marketplace อาเซียน',phases:['สมัครบัญชี (6)','ตั้งค่าโปรไฟล์ (5)','ลงประกาศขาย (7)','โปรโมทสินค้า (3)','รับออร์เดอร์ (5)','ตรวจสอบชำระเงิน (4)','จัดส่ง (4)','หลังการขาย (3)']},
  {id:'mudah',name:'Mudah',color:'#FFB800',icon:'MY',steps:40,sections:7,users:'12M+',desc:'Classifieds อันดับ 1 มาเลเซีย',phases:['สมัครบัญชี (6)','ตั้งค่าโปรไฟล์ (4)','ลงประกาศขาย (7)','โปรโมท (3)','รับออร์เดอร์ (6)','ชำระเงินจัดส่ง (5)','หลังการขาย (3)']},
  {id:'zalora',name:'Zalora',color:'#000000',icon:'SG',steps:55,sections:9,users:'40M+',desc:'Fashion E-commerce อันดับ 1 อาเซียน',phases:['สมัคร Seller (7)','ยืนยันตัวตน (5)','เพิ่มสินค้า (8)','ตั้งค่าจัดส่ง (4)','โปรโมชั่น (5)','รับออร์เดอร์ (5)','ชำระเงิน (5)','จัดส่ง (5)','หลังการขาย (4)']},
  {id:'tiki',name:'Tiki',color:'#1A94FF',icon:'VN',steps:58,sections:9,users:'20M+',desc:'Marketplace อันดับ 2 เวียดนาม',phases:['สมัคร Seller (6)','เปิดร้านค้า (7)','ยืนยันตัวตน (5)','เพิ่มสินค้า (8)','โปรโมชั่น (5)','รับออร์เดอร์ (5)','ชำระเงิน (5)','จัดส่ง (5)','หลังการขาย (4)']},
  {id:'bukalapak',name:'Bukalapak',color:'#E31E52',icon:'ID',steps:60,sections:10,users:'70M+',desc:'Marketplace อันดับ 3 อินโดนีเซีย',phases:['สมัครบัญชี (6)','เปิดร้าน Pelapak (6)','ยืนยันตัวตน (5)','การเงิน (4)','เพิ่มสินค้า (8)','จัดส่ง (4)','โปรโมชั่น (5)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'jd',name:'JD',color:'#E1251B',icon:'CN',steps:65,sections:10,users:'580M+',desc:'E-commerce อันดับ 2 จีน (京东)',phases:['เตรียมตัว (5)','สมัคร JD Seller (7)','ตั้งค่าร้าน (6)','เพิ่มสินค้า (8)','โปรโมชั่น (5)','JD Ads (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','จัดส่ง JD Logistics (5)','หลังการขาย (5)']},
  {id:'secoo',name:'Secoo',color:'#C4A265',icon:'CN',steps:55,sections:9,users:'50M+',desc:'Luxury E-commerce จีน (寺库)',phases:['เตรียมตัว (5)','สมัคร Seller (7)','ตั้งค่าร้าน (5)','เพิ่มสินค้า (8)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','จัดส่ง (5)','หลังการขาย (4)']},
  {id:'xianyu',name:'Xianyu',color:'#FFD700',icon:'CN',steps:48,sections:8,users:'300M+',desc:'C2C มือสอง Alibaba (闲鱼)',phases:['สมัครบัญชี (6)','ตั้งค่าโปรไฟล์ (5)','ลงขายสินค้า (7)','สื่อสารต่อรอง (5)','ชำระเงิน Alipay (4)','จัดส่ง (5)','หลังการขาย (4)','Fish Ponds ชุมชน (4)']},
  {id:'dianping',name:'Dianping',color:'#FF6633',icon:'CN',steps:55,sections:9,users:'400M+',desc:'Review + ร้านอาหาร (大众点评)',phases:['สมัครบัญชี (6)','สมัครร้านค้า (7)','ตั้งค่าร้าน (6)','เพิ่มเมนู (6)','โปรโมท (5)','Ads (4)','รับลูกค้า (5)','ชำระเงิน (4)','รีวิว (5)']},
  {id:'meituan',name:'Meituan',color:'#FFD100',icon:'CN',steps:58,sections:9,users:'680M+',desc:'Food + Service Platform (美团)',phases:['สมัครบัญชี (6)','สมัคร Merchant (7)','ตั้งค่าร้าน (6)','เพิ่มเมนู (7)','โปรโมชั่น (5)','Ads (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (5)']},
  {id:'eleme',name:'Eleme',color:'#009FE8',icon:'CN',steps:52,sections:8,users:'300M+',desc:'Food Delivery (饿了么) Alibaba',phases:['สมัครบัญชี (6)','สมัคร Merchant (7)','ตั้งค่าร้าน (6)','เพิ่มเมนู (7)','โปรโมชั่น (4)','รับออร์เดอร์ (5)','ชำระเงิน (5)','หลังการขาย (4)']},
  {id:'toutiao',name:'Toutiao',color:'#F85959',icon:'CN',steps:50,sections:8,users:'700M+',desc:'News/Content (今日头条) ByteDance',phases:['สมัครบัญชี (6)','สมัคร Creator (5)','ตั้งค่าโปรไฟล์ (5)','สร้าง Content (7)','Ads (4)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (4)']},
  {id:'baijiahao',name:'Baijiahao',color:'#2932E1',icon:'CN',steps:45,sections:7,users:'500M+',desc:'Baidu Content (百家号)',phases:['สมัครบัญชี (6)','ยืนยันตัวตน (4)','ตั้งค่าโปรไฟล์ (5)','สร้าง Content SEO (8)','Ads (4)','ดึง Traffic (5)','หลังการขาย (4)']},
  {id:'kr36',name:'Kr36',color:'#0064FF',icon:'CN',steps:38,sections:6,users:'20M+',desc:'Tech/Startup Media (36氪)',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (4)','สร้าง Content (7)','Ads (5)','ดึง Traffic (4)','หลังการขาย (3)']},
  {id:'hupu',name:'Hupu',color:'#D3272C',icon:'CN',steps:42,sections:7,users:'80M+',desc:'Sports Community (虎扑)',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (4)','เข้าร่วม Community (5)','สร้าง Content (7)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (4)']},
  {id:'netease',name:'Netease',color:'#D43C33',icon:'CN',steps:45,sections:7,users:'800M+',desc:'Portal + Content (网易)',phases:['สมัครบัญชี (5)','สมัคร Creator (5)','สร้าง Content (7)','Ads (4)','ดึง Traffic (5)','Kaola Cross-border (5)','หลังการขาย (4)']},
  {id:'youku',name:'Youku',color:'#1890FF',icon:'CN',steps:48,sections:8,users:'500M+',desc:'Video Platform Alibaba (优酷)',phases:['สมัครบัญชี (6)','สมัคร Creator (5)','ตั้งค่า Channel (5)','สร้างวิดีโอ (7)','Ads (4)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (4)']},
  {id:'tencentvideo',name:'TencentVideo',color:'#FF6A00',icon:'CN',steps:48,sections:8,users:'600M+',desc:'Video Platform Tencent (腾讯视频)',phases:['สมัครบัญชี (6)','สมัคร Creator (5)','ตั้งค่า Channel (5)','สร้างวิดีโอ (7)','Ads (4)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (4)']},
  {id:'mangotv',name:'MangoTV',color:'#FF8C00',icon:'CN',steps:45,sections:7,users:'300M+',desc:'Video + Entertainment (芒果TV)',phases:['สมัครบัญชี (6)','สมัคร Creator (5)','สร้างวิดีโอ (7)','Marketing (5)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (4)']},
  {id:'huya',name:'Huya',color:'#FFCA28',icon:'CN',steps:45,sections:7,users:'200M+',desc:'Game Streaming (虎牙)',phases:['สมัครบัญชี (6)','สมัคร Streamer (5)','ตั้งค่า Channel (5)','Live Streaming (7)','Gift+Ads (5)','ดึง Traffic (5)','หลังการขาย (4)']},
  {id:'douyu',name:'Douyu',color:'#FF6600',icon:'CN',steps:45,sections:7,users:'150M+',desc:'Game Streaming (斗鱼)',phases:['สมัครบัญชี (6)','สมัคร Streamer (5)','ตั้งค่า Channel (5)','Live Streaming (7)','Gift+Ads (5)','ดึง Traffic (5)','หลังการขาย (4)']},
  {id:'inke',name:'Inke',color:'#FF3366',icon:'CN',steps:42,sections:7,users:'100M+',desc:'Live Streaming (映客)',phases:['สมัครบัญชี (6)','สมัคร Streamer (5)','ตั้งค่า Channel (5)','Live+ขายของ (6)','Gift Revenue (4)','ดึง Traffic (5)','หลังการขาย (4)']},
  {id:'neteasemusic',name:'NeteaseMusic',color:'#C20C0C',icon:'CN',steps:40,sections:6,users:'800M+',desc:'Music Platform (网易云音乐)',phases:['สมัครบัญชี (5)','สมัคร Creator (5)','สร้าง Audio Content (7)','Community (5)','ดึง Traffic (5)','หลังการขาย (3)']},
  {id:'ximalaya',name:'Ximalaya',color:'#F55B23',icon:'CN',steps:42,sections:7,users:'600M+',desc:'Podcast อันดับ 1 จีน (喜马拉雅)',phases:['สมัครบัญชี (5)','สมัคร Creator (5)','ตั้งค่า Channel (5)','สร้าง Audio (7)','โปรโมท (4)','ดึง Traffic (5)','หลังการขาย (3)']},
  {id:'kugou',name:'Kugou',color:'#2681FF',icon:'CN',steps:38,sections:6,users:'400M+',desc:'Music Platform (酷狗音乐)',phases:['สมัครบัญชี (5)','สมัคร Creator (5)','สร้าง Content (6)','Live Streaming (5)','ดึง Traffic (5)','หลังการขาย (3)']},
  {id:'maimai',name:'Maimai',color:'#0066FF',icon:'CN',steps:40,sections:6,users:'100M+',desc:'LinkedIn จีน (脉脉)',phases:['สมัครบัญชี (5)','โปรไฟล์ธุรกิจ (6)','Content B2B (7)','Networking (5)','ดึง Traffic B2B (5)','หลังการขาย (3)']},
  {id:'keep',name:'KeepFitness',color:'#35C5F0',icon:'CN',steps:42,sections:7,users:'300M+',desc:'Fitness App + Keep Mall',phases:['สมัครบัญชี (5)','สมัคร Creator (5)','Fitness Content (6)','Keep Mall ขายสินค้า (6)','โปรโมท (4)','ดึง Traffic (5)','หลังการขาย (3)']},
  {id:'mint',name:'Mint',color:'#4CAF50',icon:'CN',steps:38,sections:6,users:'50M+',desc:'Health/Diet App (薄荷健康)',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (5)','Health Content (6)','Mint Mall (5)','ดึง Traffic (5)','หลังการขาย (3)']},
  {id:'orami',name:'Orami',color:'#FF6B9D',icon:'ID',steps:40,sections:7,users:'10M+',desc:'แม่และเด็ก Platform อินโดนีเซีย',phases:['สมัครบัญชี (5)','ตั้งค่าโปรไฟล์ (4)','Content แม่และเด็ก (6)','Community (5)','ดึง Traffic (5)','รับออร์เดอร์ (5)','หลังการขาย (3)']}
];

let created = 0;
platforms.forEach(p => {
  const html = `<!-- Openthai.ai - ${p.name} Roadmap -->\n<section id="${p.id}-roadmap" style="max-width:900px;margin:2rem auto;padding:2rem;font-family:'Sarabun',sans-serif;background:#f8f9fa;border-radius:16px;">\n<h2 style="text-align:center;color:${p.color};font-size:2rem;">${p.icon} ${p.name} — ${p.steps} ขั้นตอน</h2>\n<p style="text-align:center;color:#666;">${p.desc} | ${p.users} Users</p>\n<div style="background:#fff;padding:1.5rem;border-radius:12px;border-left:4px solid ${p.color};margin-top:1rem;">\n<ol>${p.phases.map((ph,i) => `<li style="padding:4px 0;"><strong>ส่วนที่ ${i+1}</strong> — ${ph}</li>`).join('\n')}</ol>\n</div>\n<div style="text-align:center;margin-top:1.5rem;padding:1rem;background:${p.color};border-radius:12px;">\n<p style="color:#fff;margin:0;">🤖 Openthai.ai ช่วยสร้าง Content ได้ทุกภาษา</p>\n<a href="/generate" style="display:inline-block;margin-top:8px;padding:10px 24px;background:#fff;color:${p.color};border-radius:20px;text-decoration:none;font-weight:bold;">สร้าง Content ${p.name} →</a>\n</div>\n</section>`;
  fs.writeFileSync(dir + '/' + p.id + '-roadmap-section.html', html);

  const guide = `<html><head><meta charset="utf-8"><style>body{font-family:Sarabun,sans-serif;max-width:700px;margin:0 auto;padding:20px;line-height:1.6}h1{color:${p.color};border-bottom:3px solid ${p.color}}h3{margin-top:16px}</style></head><body><h1>${p.icon} ${p.name} Roadmap</h1><p>${p.desc} | ${p.users}</p><p><strong>${p.steps} ขั้นตอน | ${p.sections} ส่วน</strong></p>${p.phases.map((ph,i) => `<h3>ส่วนที่ ${i+1} — ${ph}</h3>`).join('')}<hr><p><em>สร้างโดย Openthai.ai — www.OpenThaiAi.com</em></p></body></html>`;
  fs.writeFileSync(dir + '/Openthai.ai_' + p.name + '_Roadmap.html', guide);

  created++;
  console.log(created + '. ' + p.name + ': HTML section + Guide ✓');
});

console.log('\n=== DONE: ' + created + ' platforms ===');
