#!/usr/bin/env node
// Openthai.ai — SDK Generator (Stainless-style)
//
// Reads openapi.js and auto-generates frontend/src/sdk/openthaiClient.js
// Usage: node backend/sdk-gen.js
//
// Run this whenever the API changes to keep the SDK in sync.

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { openapiSpec } from './openapi.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR  = join(__dirname, '../frontend/src/sdk');
const OUT_FILE = join(OUT_DIR, 'openthaiClient.js');

// ── Helpers ──────────────────────────────────────────────────────────────────

function toCamel(str) {
  // kebab-case and snake_case → camelCase, e.g. "generate-ab" → "generateAb"
  return str.replace(/[-_](.)/g, (_, c) => c.toUpperCase());
}

function pathToMethodName(method, path) {
  // POST /api/generate        → generate
  // GET  /api/trending        → getTrending
  // POST /api/generate-ab     → generateAb
  // POST /api/agent/{id}/run  → runAgent
  // DELETE /api/agent/{id}    → deleteAgent
  const parts = path
    .replace(/^\/api\//, '')
    .replace(/\{[^}]+\}/g, '')        // remove path params
    .replace(/\/+$/, '')              // trailing slash
    .split('/')
    .filter(Boolean)
    .map((s, i) => {
      const camel = toCamel(s);
      return i === 0 ? camel : camel.charAt(0).toUpperCase() + camel.slice(1);
    })
    .join('');

  if (method === 'get')    return 'get'    + parts.charAt(0).toUpperCase() + parts.slice(1);
  if (method === 'delete') return 'delete' + parts.charAt(0).toUpperCase() + parts.slice(1);
  if (method === 'patch')  return 'update' + parts.charAt(0).toUpperCase() + parts.slice(1);
  return parts;
}

function extractPathParams(path) {
  const matches = path.match(/\{([^}]+)\}/g) || [];
  return matches.map(m => m.slice(1, -1));
}

function buildJsDoc(op, method, path, pathParams) {
  const lines = ['/**'];
  if (op.summary) lines.push(` * ${op.summary}`);
  if (op.description) {
    op.description.split('\n').forEach(l => lines.push(` * ${l}`));
  }
  lines.push(` * @method ${method.toUpperCase()} ${path}`);
  if (op.tags?.length) lines.push(` * @tag ${op.tags.join(', ')}`);
  pathParams.forEach(p => lines.push(` * @param {string} ${p} — path parameter`));
  if (method !== 'get' && method !== 'delete') {
    lines.push(' * @param {Object} body — request body');
  }
  if (op.security?.length) lines.push(' * @requires BearerAuth — set client.token first');
  lines.push(' */');
  return lines.join('\n');
}

// ── Code generator ────────────────────────────────────────────────────────────

function generateSdk(spec) {
  const methods = [];

  for (const [path, pathItem] of Object.entries(spec.paths)) {
    for (const [httpMethod, op] of Object.entries(pathItem)) {
      if (typeof op !== 'object' || !op.responses) continue;

      const pathParams = extractPathParams(path);
      const methodName = pathToMethodName(httpMethod, path);

      // Build JS path string: /api/agent/{id}/run → `/api/agent/${id}/run`
      const jsPath = path.replace(/\{([^}]+)\}/g, '${$1}');

      const hasBody = ['post', 'put', 'patch'].includes(httpMethod);
      const needsAuth = op.security?.length > 0;

      const jsdoc = buildJsDoc(op, httpMethod, path, pathParams);

      // Function signature
      const paramList = [
        ...pathParams,
        ...(hasBody ? ['body = {}'] : []),
        'opts = {}',
      ].join(', ');

      const fetchUrl = jsPath.includes('${') ? `\`\${this._base}${jsPath}\`` : `\`\${this._base}${jsPath}\``;

      let fnBody = `    const url = ${fetchUrl};\n`;
      fnBody += `    return this._req('${httpMethod.toUpperCase()}', url, ${hasBody ? 'body' : 'null'}, ${needsAuth ? 'true' : 'false'}, opts);\n`;

      methods.push(`  ${jsdoc}\n  ${methodName}(${paramList}) {\n${fnBody}  }`);
    }
  }

  const banner = `// ─────────────────────────────────────────────────────────────────────────────
// Openthai.ai — JavaScript SDK
// AUTO-GENERATED by backend/sdk-gen.js — DO NOT EDIT MANUALLY
// Regenerate: node backend/sdk-gen.js
//
// Source spec: OpenAPI ${spec.info.version}
// Generated:   ${new Date().toISOString()}
// ─────────────────────────────────────────────────────────────────────────────
`;

  const classCode = `
export class OpenThaiClient {
  /**
   * @param {Object} options
   * @param {string} [options.baseUrl] — API base URL (default: same-origin /api via proxy)
   * @param {string} [options.token]   — JWT token for authenticated endpoints
   */
  constructor({ baseUrl = '', token = '' } = {}) {
    this._base  = baseUrl.replace(/\\/$/, '');
    this.token  = token;
  }

  // ── Internal request helper ────────────────────────────────────────────────

  async _req(method, url, body, requiresAuth, opts = {}) {
    const headers = { 'Content-Type': 'application/json', ...opts.headers };
    if (requiresAuth && this.token) {
      headers['Authorization'] = \`Bearer \${this.token}\`;
    }
    const fetchOpts = { method, headers, ...opts };
    if (body !== null) fetchOpts.body = JSON.stringify(body);

    const res = await fetch(url, fetchOpts);

    // TTS returns binary audio — return Response directly
    const ct = res.headers.get('content-type') || '';
    if (ct.startsWith('audio/')) return res;

    const text = await res.text();
    let data;
    try { data = JSON.parse(text); } catch { data = { raw: text }; }

    if (!res.ok) {
      const err = new Error(data?.error || data?.message || \`HTTP \${res.status}\`);
      err.status = res.status;
      err.data   = data;
      throw err;
    }
    return data;
  }

${methods.join('\n\n')}
}

// ── Convenience singleton (configure via env / import.meta.env) ───────────────
//
//   import { client } from './sdk/openthaiClient.js';
//   client.token = localStorage.getItem('auth_token');
//   const result = await client.generate({ product: 'น้ำพริกแม่บ้าน' });

export const client = new OpenThaiClient({
  baseUrl: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_URL)
    ? import.meta.env.VITE_API_URL
    : '',
});
`;

  return banner + classCode;
}

// ── Write output ─────────────────────────────────────────────────────────────

function run() {
  if (!existsSync(OUT_DIR)) {
    mkdirSync(OUT_DIR, { recursive: true });
    console.log(`📁 Created ${OUT_DIR}`);
  }

  const code = generateSdk(openapiSpec);
  writeFileSync(OUT_FILE, code, 'utf8');

  const endpointCount = Object.values(openapiSpec.paths)
    .flatMap(p => Object.values(p))
    .filter(o => o?.responses)
    .length;

  console.log(`✅ SDK generated → ${OUT_FILE}`);
  console.log(`   ${endpointCount} endpoints | ${openapiSpec.info.version} spec`);
  console.log(`\n   Usage in frontend:`);
  console.log(`   import { client } from './sdk/openthaiClient.js';`);
  console.log(`   const result = await client.generate({ product: 'น้ำพริก' });`);
}

run();
