"""OpenThai eTax / XAdES Verification API Gateway — v1.5.1-dev

Endpoints:
  GET  /health
  POST /api/v1/verify
  GET  /docs   (Swagger UI, auto-generated by FastAPI)
"""
import base64
import logging
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))

import asyncio
import time
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, field_validator

from xades_engine import VERSION, XAdESVerifier, XAdESVerificationError

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
logger = logging.getLogger("openthai_api")

app = FastAPI(
    title="OpenThai eTax / XAdES Verification API",
    version=VERSION,
    description="Enterprise XAdES-BES/EPES/T/A signature verification for Thai e-Tax documents",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8090", "http://127.0.0.1:8090", "http://localhost:3000", "*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_verifier_no_revoc = XAdESVerifier()
_verifier_with_revoc = XAdESVerifier(check_revocation=True)


class VerifyRequest(BaseModel):
    document_id: str = Field(..., example="INV-2026-0001")
    xml_base64: str = Field(..., description="e-Tax Invoice XML encoded as Base64")
    tsa_der_base64: Optional[str] = Field(None, description="RFC 3161 TSA token (Base64 DER), optional")
    require_timestamp: bool = Field(False, description="Reject documents without XAdES-T timestamp")
    check_revocation: bool = Field(False, description="Enable live OCSP/CRL revocation check (requires network)")


class VerifyResponse(BaseModel):
    status: str
    document_id: str
    xades_profile: str
    is_valid: bool
    elapsed_ms: Optional[float] = None
    verification_details: dict


class BatchVerifyRequest(BaseModel):
    documents: List[VerifyRequest] = Field(..., max_length=500)
    require_timestamp: bool = Field(False)
    check_revocation: bool = Field(False)

    @field_validator("documents")
    @classmethod
    def at_least_one(cls, v: list) -> list:
        if not v:
            raise ValueError("documents ต้องมีอย่างน้อย 1 รายการ")
        return v


class BatchVerifyResponse(BaseModel):
    total: int
    passed: int
    failed: int
    elapsed_ms: float
    results: List[VerifyResponse]


@app.get("/health")
def health() -> dict:
    from xades_engine.c14n_fast import is_rust_active, engine_version
    return {
        "status": "UP",
        "engine_version": VERSION,
        "c14n_backend": engine_version(),
        "rust_c14n_active": is_rust_active(),
        "supported_profiles": ["XAdES-BES", "XAdES-EPES", "XAdES-T", "XAdES-A"],
    }


def _do_verify(req: VerifyRequest) -> VerifyResponse:
    """Shared verify logic used by both single and batch endpoints."""
    t0 = time.perf_counter()
    try:
        xml_bytes = base64.b64decode(req.xml_base64)
        tsa_bytes = base64.b64decode(req.tsa_der_base64) if req.tsa_der_base64 else None
        verifier = _verifier_with_revoc if req.check_revocation else _verifier_no_revoc
        result = verifier.verify(xml_bytes, tsa_token_der=tsa_bytes,
                                 require_timestamp=req.require_timestamp)
        return VerifyResponse(
            status="SUCCESS",
            document_id=req.document_id,
            xades_profile=result.get("xades_profile", "XAdES-BES"),
            is_valid=result.get("is_valid", False),
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 2),
            verification_details=result,
        )
    except XAdESVerificationError as exc:
        logger.warning("Verification rejected [%s]: %s", req.document_id, exc)
        return VerifyResponse(
            status="VERIFICATION_FAILED",
            document_id=req.document_id,
            xades_profile="UNKNOWN",
            is_valid=False,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 2),
            verification_details={"error": str(exc)},
        )
    except Exception as exc:
        logger.error("Internal error [%s]: %s", req.document_id, exc, exc_info=True)
        return VerifyResponse(
            status="INTERNAL_ERROR",
            document_id=req.document_id,
            xades_profile="UNKNOWN",
            is_valid=False,
            elapsed_ms=round((time.perf_counter() - t0) * 1000, 2),
            verification_details={"error": f"Internal error: {exc}"},
        )


@app.post("/api/v1/verify", response_model=VerifyResponse)
def verify(req: VerifyRequest) -> VerifyResponse:
    """ตรวจสอบลายมือชื่ออิเล็กทรอนิกส์ XAdES บนใบกำกับภาษี e-Tax ใบเดียว"""
    return _do_verify(req)


@app.post("/api/v1/verify-batch", response_model=BatchVerifyResponse)
def verify_batch(req: BatchVerifyRequest) -> BatchVerifyResponse:
    """ตรวจสอบ XAdES พร้อมกันสูงสุด 500 ใบต่อครั้ง (parallel processing)

    เหมาะสำหรับระบบที่ต้องการ throughput สูง เช่น ERP รับใบจาก supplier จำนวนมาก
    """
    from concurrent.futures import ThreadPoolExecutor, as_completed

    t0 = time.perf_counter()
    # override per-doc flags from batch-level flags
    docs = []
    for doc in req.documents:
        d = doc.model_copy(update={
            "require_timestamp": req.require_timestamp,
            "check_revocation": req.check_revocation,
        })
        docs.append(d)

    results: List[VerifyResponse] = []
    max_workers = min(len(docs), 16)
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {pool.submit(_do_verify, d): d for d in docs}
        for future in as_completed(futures):
            results.append(future.result())

    elapsed = round((time.perf_counter() - t0) * 1000, 2)
    passed = sum(1 for r in results if r.is_valid)

    logger.info(
        "Batch verify: %d/%d passed in %.0f ms (%.0f docs/s)",
        passed, len(results), elapsed, len(results) / (elapsed / 1000) if elapsed else 0,
    )
    return BatchVerifyResponse(
        total=len(results),
        passed=passed,
        failed=len(results) - passed,
        elapsed_ms=elapsed,
        results=results,
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
