#!/usr/bin/env bash
# session-end.sh — รันอัตโนมัติเมื่อ Claude Code session จบ
# บันทึกสรุปงานวันนี้ → commit → push

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DATE_TH=$(TZ='Asia/Bangkok' date '+%Y-%m-%d')
TIME_TH=$(TZ='Asia/Bangkok' date '+%H:%M')
OUTDIR="$REPO_DIR/docs/conversations"
OUTFILE="$OUTDIR/${DATE_TH}_${TIME_TH//:/_}_summary.md"

mkdir -p "$OUTDIR"
cd "$REPO_DIR"

# ── 1. Commits วันนี้ ─────────────────────────────────────────────
COMMITS=$(git log --oneline --since="$DATE_TH 00:00" --until="$DATE_TH 23:59" 2>/dev/null || echo "ไม่มี commit วันนี้")

# ── 2. ไฟล์ที่เปลี่ยนแปลง ─────────────────────────────────────────
CHANGED=$(git diff --name-only HEAD~5..HEAD 2>/dev/null | head -20 || echo "-")

# ── 3. Branch ปัจจุบัน ───────────────────────────────────────────
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# ── 4. เขียนไฟล์สรุป ─────────────────────────────────────────────
cat > "$OUTFILE" << SUMMARY
# สรุปงานประจำวัน — Openthai.ai
**วันที่:** $DATE_TH | **เวลา:** $TIME_TH น. (Bangkok)
**Branch:** $BRANCH

---

## ✅ Commits วันนี้

\`\`\`
$COMMITS
\`\`\`

---

## 📁 ไฟล์ที่เปลี่ยนแปลง

\`\`\`
$CHANGED
\`\`\`

---

## 📌 Context สำหรับ session ถัดไป

> อ่าน CLAUDE.md และไฟล์นี้ก่อนเริ่มงานใหม่

- ภาษาไทยเป็นหลัก
- ห้าม MLM / sub-affiliate ถาวร
- Branch: $BRANCH
- Push แล้ว: ✅

---
*Auto-generated by session-end.sh — $DATE_TH $TIME_TH*
SUMMARY

# ── 5. บันทึกใน sync-log ────────────────────────────────────────
echo "[$DATE_TH $TIME_TH] session-end: auto-summary saved" >> "$REPO_DIR/docs/sync-log.txt"

# ── 6. Commit + Push ─────────────────────────────────────────────
git add "$OUTFILE" "$REPO_DIR/docs/sync-log.txt" "$REPO_DIR/CLAUDE.md" 2>/dev/null || true
git diff --cached --quiet && echo "[session-end] ไม่มีไฟล์ใหม่ ข้าม commit" && exit 0

git commit -m "session: auto-save $DATE_TH $TIME_TH — daily summary" 2>/dev/null || true
git push origin "$BRANCH" 2>/dev/null || echo "[session-end] push ไม่สำเร็จ — บันทึกไว้ใน local แล้ว"

echo ""
echo "════════════════════════════════════════"
echo "  📋 สรุปงานวันนี้บันทึกแล้ว"
echo "  📁 $OUTFILE"
echo "  🕐 $DATE_TH $TIME_TH น."
echo "════════════════════════════════════════"
echo ""
echo "  Commits วันนี้:"
echo "$COMMITS" | sed 's/^/    /'
echo ""
echo "  ✅ Push ไปยัง GitHub แล้ว"
echo "════════════════════════════════════════"
