// ─────────────────────────────────────────────────────────────────────────────
// OpenThaiAi — JavaScript SDK
// AUTO-GENERATED by backend/sdk-gen.js — DO NOT EDIT MANUALLY
// Regenerate: node backend/sdk-gen.js
//
// Source spec: OpenAPI 2.0.0
// Generated:   2026-05-20T13:33:14.026Z
// ─────────────────────────────────────────────────────────────────────────────

export class OpenThaiClient {
  /**
   * @param {Object} options
   * @param {string} [options.baseUrl] — API base URL (default: same-origin /api via proxy)
   * @param {string} [options.token]   — JWT token for authenticated endpoints
   */
  constructor({ baseUrl = '', token = '' } = {}) {
    this._base  = baseUrl.replace(/\/$/, '');
    this.token  = token;
  }

  // ── Internal request helper ────────────────────────────────────────────────

  async _req(method, url, body, requiresAuth, opts = {}) {
    const headers = { 'Content-Type': 'application/json', ...opts.headers };
    if (requiresAuth && this.token) {
      headers['Authorization'] = `Bearer ${this.token}`;
    }
    const fetchOpts = { method, headers, ...opts };
    if (body !== null) fetchOpts.body = JSON.stringify(body);

    const res = await fetch(url, fetchOpts);

    // TTS returns binary audio — return Response directly
    const ct = res.headers.get('content-type') || '';
    if (ct.startsWith('audio/')) return res;

    const text = await res.text();
    let data;
    try { data = JSON.parse(text); } catch { data = { raw: text }; }

    if (!res.ok) {
      const err = new Error(data?.error || data?.message || `HTTP ${res.status}`);
      err.status = res.status;
      err.data   = data;
      throw err;
    }
    return data;
  }

  /**
 * Generate Thai social media content
 * Generates hook, script, caption, and hashtags optimised for Thai products. Uses Claude → Gemini → Mock fallback chain.
 * @method POST /api/generate
 * @tag AI Generation
 * @param {Object} body — request body
 */
  generate(body = {}, opts = {}) {
    const url = `${this._base}/api/generate`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * A/B test — generate 2 content variants
 * Returns variant A (original style) and variant B (opposite style) simultaneously.
 * @method POST /api/generate-ab
 * @tag AI Generation
 * @param {Object} body — request body
 */
  generateAb(body = {}, opts = {}) {
    const url = `${this._base}/api/generate-ab`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Analyze product image with AI vision
 * Extracts product name, category, description, and target audience from an image using Claude/Gemini vision.
 * @method POST /api/analyze-image
 * @tag AI Generation
 * @param {Object} body — request body
 */
  analyzeImage(body = {}, opts = {}) {
    const url = `${this._base}/api/analyze-image`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Get trending Thai hashtags and topics
 * Returns trending hashtags, topics, and sounds. Cached 30 min. Uses Gemini AI to generate real-time trends when available.
 * @method GET /api/trending
 * @tag Trending
 */
  getTrending(opts = {}) {
    const url = `${this._base}/api/trending`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * Get news-based content ideas (RAG)
 * Fetches Thai news headlines from RSS feeds (Thairath, Sanook) and converts them into content ideas. Cached 1 hour.
 * @method GET /api/news-rag
 * @tag Trending
 */
  getNewsRag(opts = {}) {
    const url = `${this._base}/api/news-rag`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * Analyze competitor strategy in a niche
 * AI-powered competitor analysis: tactics, content gaps, winning hooks, and recommended angles.
 * @method POST /api/competitor-analyze
 * @tag Trending
 * @param {Object} body — request body
 */
  competitorAnalyze(body = {}, opts = {}) {
    const url = `${this._base}/api/competitor-analyze`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * List all AI agents
 * @method GET /api/agent
 * @tag Agent
 * @requires BearerAuth — set client.token first
 */
  getAgent(opts = {}) {
    const url = `${this._base}/api/agent`;
    return this._req('GET', url, null, true, opts);
  }

  /**
 * Create a new AI agent
 * @method POST /api/agent
 * @tag Agent
 * @param {Object} body — request body
 * @requires BearerAuth — set client.token first
 */
  agent(body = {}, opts = {}) {
    const url = `${this._base}/api/agent`;
    return this._req('POST', url, body, true, opts);
  }

  /**
 * Manually trigger an agent run
 * @method POST /api/agent/{id}/run
 * @tag Agent
 * @param {string} id — path parameter
 * @param {Object} body — request body
 * @requires BearerAuth — set client.token first
 */
  agentRun(id, body = {}, opts = {}) {
    const url = `${this._base}/api/agent/${id}/run`;
    return this._req('POST', url, body, true, opts);
  }

  /**
 * Apply for affiliate program
 * @method POST /api/affiliate/apply
 * @tag Affiliate
 * @param {Object} body — request body
 */
  affiliateApply(body = {}, opts = {}) {
    const url = `${this._base}/api/affiliate/apply`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Get affiliate stats by ref code
 * @method GET /api/affiliate/stats/{ref_code}
 * @tag Affiliate
 * @param {string} ref_code — path parameter
 */
  getAffiliateStats(ref_code, opts = {}) {
    const url = `${this._base}/api/affiliate/stats/${ref_code}`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * Send LINE message to a user
 * @method POST /api/line/send
 * @tag Integrations
 * @param {Object} body — request body
 */
  lineSend(body = {}, opts = {}) {
    const url = `${this._base}/api/line/send`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Check LINE OA connection status
 * @method GET /api/line/status
 * @tag Integrations
 */
  getLineStatus(opts = {}) {
    const url = `${this._base}/api/line/status`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * Text-to-speech via ElevenLabs
 * @method POST /api/tts
 * @tag Integrations
 * @param {Object} body — request body
 */
  tts(body = {}, opts = {}) {
    const url = `${this._base}/api/tts`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Health check
 * Returns API status, AI engine, active services, and resource usage.
 * @method GET /api/health
 * @tag System
 */
  getHealth(opts = {}) {
    const url = `${this._base}/api/health`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * System metrics (agents, runs, scores, memory)
 * @method GET /api/system/metrics
 * @tag System
 */
  getSystemMetrics(opts = {}) {
    const url = `${this._base}/api/system/metrics`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * System event logs
 * @method GET /api/system/logs
 * @tag System
 */
  getSystemLogs(opts = {}) {
    const url = `${this._base}/api/system/logs`;
    return this._req('GET', url, null, false, opts);
  }

  /**
 * AI-powered self-diagnosis
 * Analyzes recent errors and warns, returns health_score and recommendations.
 * @method POST /api/system/diagnose
 * @tag System
 * @param {Object} body — request body
 */
  systemDiagnose(body = {}, opts = {}) {
    const url = `${this._base}/api/system/diagnose`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Manually trigger watchdog auto-heal
 * @method POST /api/system/auto-heal
 * @tag System
 * @param {Object} body — request body
 */
  systemAutoHeal(body = {}, opts = {}) {
    const url = `${this._base}/api/system/auto-heal`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Login with password or Google OAuth
 * @method POST /api/auth/login
 * @tag Auth
 * @param {Object} body — request body
 */
  authLogin(body = {}, opts = {}) {
    const url = `${this._base}/api/auth/login`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Verify JWT token
 * @method GET /api/auth/verify
 * @tag Auth
 * @requires BearerAuth — set client.token first
 */
  getAuthVerify(opts = {}) {
    const url = `${this._base}/api/auth/verify`;
    return this._req('GET', url, null, true, opts);
  }

  /**
 * Record PDPA consent (มาตรา 19)
 * @method POST /api/privacy/consent
 * @tag Privacy
 * @param {Object} body — request body
 */
  privacyConsent(body = {}, opts = {}) {
    const url = `${this._base}/api/privacy/consent`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Request data erasure (Right to be forgotten — มาตรา 33)
 * @method POST /api/privacy/erasure
 * @tag Privacy
 * @param {Object} body — request body
 */
  privacyErasure(body = {}, opts = {}) {
    const url = `${this._base}/api/privacy/erasure`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Send a contact message
 * @method POST /api/contact
 * @tag System
 * @param {Object} body — request body
 */
  contact(body = {}, opts = {}) {
    const url = `${this._base}/api/contact`;
    return this._req('POST', url, body, false, opts);
  }

  /**
 * Join the waitlist
 * @method POST /api/waitlist
 * @tag System
 * @param {Object} body — request body
 */
  waitlist(body = {}, opts = {}) {
    const url = `${this._base}/api/waitlist`;
    return this._req('POST', url, body, false, opts);
  }
}

// ── Convenience singleton (configure via env / import.meta.env) ───────────────
//
//   import { client } from './sdk/openthaiClient.js';
//   client.token = localStorage.getItem('auth_token');
//   const result = await client.generate({ product: 'น้ำพริกแม่บ้าน' });

export const client = new OpenThaiClient({
  baseUrl: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_URL)
    ? import.meta.env.VITE_API_URL
    : '',
});
